sudo: false

addons:
  apt:
    packages:
      - python3-pip

language: ruby

rvm:
  - 2.2

install:
  - curl -L -o jupyter-scala https://raw.githubusercontent.com/alexarchambault/jupyter-scala/master/jupyter-scala
  - bash jupyter-scala
  - python3 -m pip install --upgrade pip
  - python3 -m pip install jupyter
  - bundle install

script: bundle exec jekyll build

deploy:
  skip_cleanup: true
  provider: pages
  local_dir: _site
  github_token: $GITHUB_PERSONAL_ACCESS_TOKEN
  repo: ThoughtWorksInc/DeepLearning.scala
