gems: [jekyll-paginate, jekyll-redirect-from, 'jekyll-multiple-languages-plugin']

name: ThoughtWorks
description: DeepLearning.scala by ThougthWorks

# News
paginate: 6
paginate_path: "/news/page:num"
future: true


assets:
  prefix: "/assets"
  digest: true

exclude:
  - README.md

languages:          ['en', 'cn']
